---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: 
  - name: metallb-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/metallb
  prune: true
  wait: true
  timeout: 5m0s
