---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb-staging
namespace: metallb-system
resources:
  - ../../base/traefik
#patchesStrategicMerge:
#  - staging-values.yaml