---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - ../../base/metallb
  - l2advertisement.yaml
  - ippool.yaml
#patchesStrategicMerge:
#  - podinfo-values.yaml