---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - namespace.yaml
  - configmap-metallb-helm-chart-value-overrides.yaml
  - repository.yaml
  - release.yaml