---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 15m0s
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb-repo
  valuesFrom:
    - kind: ConfigMap
      name: configmap-metallb-helm-chart-value-overrides
  targetNamespace: metallb-system