---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb-repo
  interval: 15m0s
  releaseName: metallb
  targetNamespace: metallb-system
  valuesFrom:
  - kind: ConfigMap
    name: configmap-metallb-helm-chart-value-overrides
    valueKey: values.yaml