---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  dependsOn:
    - name: metallb-system
  interval: 12h
  url: https://metallb.github.io/metallb

